### ISSUE TITLE
also suitable for in-place upgrades of jackrabbit or jackrabbit oak ? 

### ISSUE THREAD

**Issue by chrismade** [rombert/launchpad-update-test#1]
maybe I'm completely wrong here - if so, pls close this request with a little comment

I wonder what is the most appropriate method to in-place upgrade jackrabbit and jackrabbit oak in an existing sling environment - When downloading sling-8 from the apache sling download pages, it contains OAK 1.3.7 – whereas the latest stable version is 1.6.1 (there is also a 1.2.25 and 1.4.15 stable version available, which adds to the confusion). Same with Jackrabbit – 2.11.0 included, latest stable is  2.14.0 
In AEM oak upgrades seem to be easy - but in pure sling I can't find any procedure

Somebody had a similar request here:
http://apache-sling.73963.n3.nabble.com/upgrading-jackrabbit-and-felix-td4018420.html
was unable to see from these thread what the answer is

Is adding to the bundle list and re-make (as in this test tool) the appropriate method ?

**Comment by rombert** [comment]
Hi @chrismade ,

Upgrading Oak in Sling 8 is a bit more involved that we'd like at the moment. The story will be better with Sling 9, and we're getting ready to release that in the coming weeks.

  https://lists.apache.org/api/source.lua/b8ee7b8d72396baa6287500ad23b4ab9ff649a9d2ed3b71f72b9d44e@%3Cdev.sling.apache.org%3E

If you're looking for a quick test drive of Sling with latest Oak, I would suggest you build the launchpad module from SVN ( https://svn.apache.org/repos/asf/sling/trunk/launchpad/builder/ ), as that includes Oak 1.6.1.

If you want to upgrade Oak in Sling 8, you will probably need to build a new version of the `org.apache.sling.jcr.oak.server` ( found at https://svn.apache.org/repos/asf/sling/trunk/bundles/jcr/oak-server/ ) and deploy it in Sling alongside with the updated Oak (1.6.1) and Jackrabbit  (2.14.0) jars. That may trigger a nice chunk of repetitive work in case these new jars also require updated dependencies.

If that does not work for you I suggest you try on users@sling.apache.org, maybe someone else has done that. This project was just a small and outdated testing ground for an upgrade issue. I should retire it someday :-)

**Comment by chrismade** [comment]
Thanks, @rombert , for this comprehensive reply - I will try both ways (sling9 and sling8-upgrade) and see how it will work out - last resort:  post in the official list - thanks, again
